[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.armor"
        operation = "add"
        amount = 2.0
    [[effects.attributes]]
        name = "minecraft:generic.armor_toughness"
        operation = "add"
        amount = 2.0
    [[effects.conditions]]
        groups = ["grains"]
        match = "all"
        above = 0.9
        below = 1.0
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.attack_damage"
        operation = "add"
        amount = 2.0
    [[effects.attributes]]
        name = "minecraft:generic.attack_speed"
        operation = "multiply_base"
        amount = 0.25
    [[effects.conditions]]
        groups = ["proteins"]
        match = "all"
        above = 0.9
        below = 1.0
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.max_health"
        operation = "add"
        amount = 1.0
    [[effects.attributes]]
        name = "minecraft:generic.knockback_resistance"
        operation = "add"
        amount = 0.35
    [[effects.conditions]]
        groups = ["fruits"]
        match = "all"
        above = 0.9
        below = 1.0
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.max_health"
        operation = "add"
        amount = 1.0
    [[effects.attributes]]
        name = "minecraft:generic.knockback_resistance"
        operation = "add"
        amount = 0.35
    [[effects.conditions]]
        groups = ["vegetables"]
        match = "all"
        above = 0.9
        below = 1.0
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.max_health"
        operation = "add"
        amount = 2.0
    [[effects.conditions]]
        groups = ["proteins", "fruits", "vegetables", "grains"]
        match = "every"
        above = 0.75
        below = 1.0
[[effects]]
    [[effects.attributes]]
        name = "minecraft:generic.movement_speed"
        operation = "multiply_base"
        amount = 0.25
    [[effects.status_effects]]
        name = "minecraft:hunger"
        power = 2
    [[effects.conditions]]
        groups = ["sugars"]
        match = "all"
        above = 0.75
        below = 1.0
